//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 01:30:51 PM CET 
//


package nl.willemsenmedia.utwente.anonymization.nlp.xml_objects;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}attlist.canonicalForm"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "canonicalForm")
public class CanonicalForm {

	@XmlAttribute(name = "phraseType")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String phraseType;
	@XmlAttribute(name = "canonicalform")
	@XmlSchemaType(name = "anySimpleType")
	protected String canonicalform;
	@XmlAttribute(name = "expressionType")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String expressionType;

	/**
	 * Gets the value of the phraseType property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getPhraseType() {
		return phraseType;
	}

	/**
	 * Sets the value of the phraseType property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setPhraseType(String value) {
		this.phraseType = value;
	}

	/**
	 * Gets the value of the canonicalform property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getCanonicalform() {
		return canonicalform;
	}

	/**
	 * Sets the value of the canonicalform property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setCanonicalform(String value) {
		this.canonicalform = value;
	}

	/**
	 * Gets the value of the expressionType property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getExpressionType() {
		return expressionType;
	}

	/**
	 * Sets the value of the expressionType property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setExpressionType(String value) {
		this.expressionType = value;
	}

}
