//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 01:30:51 PM CET 
//


package nl.willemsenmedia.utwente.anonymization.nlp.xml_objects;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}attlist.Definition"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Definition")
public class Definition {

	@XmlAttribute(name = "gloss", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String gloss;
	@XmlAttribute(name = "language")
	@XmlSchemaType(name = "anySimpleType")
	protected String language;
	@XmlAttribute(name = "provenance")
	@XmlSchemaType(name = "anySimpleType")
	protected String provenance;

	/**
	 * Gets the value of the gloss property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getGloss() {
		return gloss;
	}

	/**
	 * Sets the value of the gloss property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setGloss(String value) {
		this.gloss = value;
	}

	/**
	 * Gets the value of the language property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getLanguage() {
		return language;
	}

	/**
	 * Sets the value of the language property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setLanguage(String value) {
		this.language = value;
	}

	/**
	 * Gets the value of the provenance property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getProvenance() {
		return provenance;
	}

	/**
	 * Sets the value of the provenance property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setProvenance(String value) {
		this.provenance = value;
	}

}
