//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 01:30:51 PM CET 
//


package nl.willemsenmedia.utwente.anonymization.nlp.xml_objects;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}LexicalEntry" maxOccurs="unbounded"/>
 *         &lt;element ref="{}Synset" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.Lexicon"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"lexicalEntry",
		"synset"
})
@XmlRootElement(name = "Lexicon")
public class Lexicon {

	@XmlElement(name = "LexicalEntry", required = true)
	protected List<LexicalEntry> lexicalEntry;
	@XmlElement(name = "Synset")
	protected List<Synset> synset;
	@XmlAttribute(name = "label", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NMTOKEN")
	protected String label;
	@XmlAttribute(name = "language", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NMTOKEN")
	protected String language;
	@XmlAttribute(name = "languageCoding", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String languageCoding;
	@XmlAttribute(name = "owner", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NMTOKEN")
	protected String owner;

	/**
	 * Gets the value of the lexicalEntry property.
	 * <p>
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the lexicalEntry property.
	 * <p>
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getLexicalEntry().add(newItem);
	 * </pre>
	 * <p>
	 * <p>
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link LexicalEntry }
	 */
	public List<LexicalEntry> getLexicalEntry() {
		if (lexicalEntry == null) {
			lexicalEntry = new ArrayList<LexicalEntry>();
		}
		return this.lexicalEntry;
	}

	/**
	 * Gets the value of the synset property.
	 * <p>
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the synset property.
	 * <p>
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getSynset().add(newItem);
	 * </pre>
	 * <p>
	 * <p>
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Synset }
	 */
	public List<Synset> getSynset() {
		if (synset == null) {
			synset = new ArrayList<Synset>();
		}
		return this.synset;
	}

	/**
	 * Gets the value of the label property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getLabel() {
		return label;
	}

	/**
	 * Sets the value of the label property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setLabel(String value) {
		this.label = value;
	}

	/**
	 * Gets the value of the language property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getLanguage() {
		return language;
	}

	/**
	 * Sets the value of the language property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setLanguage(String value) {
		this.language = value;
	}

	/**
	 * Gets the value of the languageCoding property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getLanguageCoding() {
		return languageCoding;
	}

	/**
	 * Sets the value of the languageCoding property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setLanguageCoding(String value) {
		this.languageCoding = value;
	}

	/**
	 * Gets the value of the owner property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getOwner() {
		return owner;
	}

	/**
	 * Sets the value of the owner property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setOwner(String value) {
		this.owner = value;
	}

}
