//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 01:30:51 PM CET 
//


package nl.willemsenmedia.utwente.anonymization.nlp.xml_objects;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}attlist.Meta"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Meta")
public class Meta {

	@XmlAttribute(name = "author")
	@XmlSchemaType(name = "anySimpleType")
	protected String author;
	@XmlAttribute(name = "confidence", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NMTOKEN")
	protected String confidence;
	@XmlAttribute(name = "date")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NMTOKEN")
	protected String date;
	@XmlAttribute(name = "source", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String source;
	@XmlAttribute(name = "status")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String status;

	/**
	 * Gets the value of the author property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * Sets the value of the author property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setAuthor(String value) {
		this.author = value;
	}

	/**
	 * Gets the value of the confidence property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getConfidence() {
		return confidence;
	}

	/**
	 * Sets the value of the confidence property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setConfidence(String value) {
		this.confidence = value;
	}

	/**
	 * Gets the value of the date property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getDate() {
		return date;
	}

	/**
	 * Sets the value of the date property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setDate(String value) {
		this.date = value;
	}

	/**
	 * Gets the value of the source property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getSource() {
		return source;
	}

	/**
	 * Sets the value of the source property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setSource(String value) {
		this.source = value;
	}

	/**
	 * Gets the value of the status property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * Sets the value of the status property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setStatus(String value) {
		this.status = value;
	}

}
