//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 01:30:51 PM CET 
//


package nl.willemsenmedia.utwente.anonymization.nlp.xml_objects;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Meta" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.MonolingualExternalRef"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"meta"
})
@XmlRootElement(name = "MonolingualExternalRef")
public class MonolingualExternalRef {

	@XmlElement(name = "Meta")
	protected Meta meta;
	@XmlAttribute(name = "externalReference", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String externalReference;
	@XmlAttribute(name = "externalSystem", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String externalSystem;
	@XmlAttribute(name = "relType")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String relType;

	/**
	 * Gets the value of the meta property.
	 *
	 * @return possible object is
	 * {@link Meta }
	 */
	public Meta getMeta() {
		return meta;
	}

	/**
	 * Sets the value of the meta property.
	 *
	 * @param value allowed object is
	 *              {@link Meta }
	 */
	public void setMeta(Meta value) {
		this.meta = value;
	}

	/**
	 * Gets the value of the externalReference property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getExternalReference() {
		return externalReference;
	}

	/**
	 * Sets the value of the externalReference property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setExternalReference(String value) {
		this.externalReference = value;
	}

	/**
	 * Gets the value of the externalSystem property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getExternalSystem() {
		return externalSystem;
	}

	/**
	 * Sets the value of the externalSystem property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setExternalSystem(String value) {
		this.externalSystem = value;
	}

	/**
	 * Gets the value of the relType property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getRelType() {
		return relType;
	}

	/**
	 * Sets the value of the relType property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setRelType(String value) {
		this.relType = value;
	}

}
