//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 01:30:51 PM CET 
//


package nl.willemsenmedia.utwente.anonymization.nlp.xml_objects;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}semanticShifts-noun" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.Semantics-noun"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"semanticShiftsNoun"
})
@XmlRootElement(name = "Semantics-noun")
public class SemanticsNoun {

	@XmlElement(name = "semanticShifts-noun")
	protected List<SemanticShiftsNoun> semanticShiftsNoun;
	@XmlAttribute(name = "countability")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String countability;
	@XmlAttribute(name = "reference")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String reference;
	@XmlAttribute(name = "semanticType")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String semanticType;
	@XmlAttribute(name = "semanticSubType")
	@XmlSchemaType(name = "anySimpleType")
	protected String semanticSubType;

	/**
	 * Gets the value of the semanticShiftsNoun property.
	 * <p>
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the semanticShiftsNoun property.
	 * <p>
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getSemanticShiftsNoun().add(newItem);
	 * </pre>
	 * <p>
	 * <p>
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link SemanticShiftsNoun }
	 */
	public List<SemanticShiftsNoun> getSemanticShiftsNoun() {
		if (semanticShiftsNoun == null) {
			semanticShiftsNoun = new ArrayList<SemanticShiftsNoun>();
		}
		return this.semanticShiftsNoun;
	}

	/**
	 * Gets the value of the countability property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getCountability() {
		return countability;
	}

	/**
	 * Sets the value of the countability property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setCountability(String value) {
		this.countability = value;
	}

	/**
	 * Gets the value of the reference property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getReference() {
		return reference;
	}

	/**
	 * Sets the value of the reference property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setReference(String value) {
		this.reference = value;
	}

	/**
	 * Gets the value of the semanticType property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getSemanticType() {
		return semanticType;
	}

	/**
	 * Sets the value of the semanticType property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setSemanticType(String value) {
		this.semanticType = value;
	}

	/**
	 * Gets the value of the semanticSubType property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getSemanticSubType() {
		return semanticSubType;
	}

	/**
	 * Sets the value of the semanticSubType property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setSemanticSubType(String value) {
		this.semanticSubType = value;
	}

}
