//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 01:30:51 PM CET 
//


package nl.willemsenmedia.utwente.anonymization.nlp.xml_objects;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}lex-collocator" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.Semantics_ex"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"lexCollocator"
})
@XmlRootElement(name = "Semantics_ex")
public class SemanticsEx {

	@XmlElement(name = "lex-collocator")
	protected List<LexCollocator> lexCollocator;
	@XmlAttribute(name = "gracol-complem")
	@XmlSchemaType(name = "anySimpleType")
	protected String gracolComplem;
	@XmlAttribute(name = "gracol-gramword")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String gracolGramword;
	@XmlAttribute(name = "definition")
	@XmlSchemaType(name = "anySimpleType")
	protected String definition;
	@XmlAttribute(name = "lexcol-speccollocator")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String lexcolSpeccollocator;

	/**
	 * Gets the value of the lexCollocator property.
	 * <p>
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the lexCollocator property.
	 * <p>
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getLexCollocator().add(newItem);
	 * </pre>
	 * <p>
	 * <p>
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link LexCollocator }
	 */
	public List<LexCollocator> getLexCollocator() {
		if (lexCollocator == null) {
			lexCollocator = new ArrayList<LexCollocator>();
		}
		return this.lexCollocator;
	}

	/**
	 * Gets the value of the gracolComplem property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getGracolComplem() {
		return gracolComplem;
	}

	/**
	 * Sets the value of the gracolComplem property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setGracolComplem(String value) {
		this.gracolComplem = value;
	}

	/**
	 * Gets the value of the gracolGramword property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getGracolGramword() {
		return gracolGramword;
	}

	/**
	 * Sets the value of the gracolGramword property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setGracolGramword(String value) {
		this.gracolGramword = value;
	}

	/**
	 * Gets the value of the definition property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getDefinition() {
		return definition;
	}

	/**
	 * Sets the value of the definition property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setDefinition(String value) {
		this.definition = value;
	}

	/**
	 * Gets the value of the lexcolSpeccollocator property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getLexcolSpeccollocator() {
		return lexcolSpeccollocator;
	}

	/**
	 * Sets the value of the lexcolSpeccollocator property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setLexcolSpeccollocator(String value) {
		this.lexcolSpeccollocator = value;
	}

}
