//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 01:30:51 PM CET 
//


package nl.willemsenmedia.utwente.anonymization.nlp.xml_objects;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}Sentiment"/>
 *         &lt;element ref="{}Pragmatics"/>
 *         &lt;choice>
 *           &lt;element ref="{}Semantics-verb"/>
 *           &lt;element ref="{}Semantics-noun"/>
 *           &lt;element ref="{}Semantics-adjective"/>
 *         &lt;/choice>
 *         &lt;element ref="{}SenseExamples"/>
 *         &lt;element ref="{}SenseRelations"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{}attlist.Sense"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"sentimentOrPragmaticsOrSemanticsVerb"
})
@XmlRootElement(name = "Sense")
public class Sense {

	@XmlElements({
			@XmlElement(name = "Sentiment", type = Sentiment.class),
			@XmlElement(name = "Pragmatics", type = Pragmatics.class),
			@XmlElement(name = "Semantics-verb", type = SemanticsVerb.class),
			@XmlElement(name = "Semantics-noun", type = SemanticsNoun.class),
			@XmlElement(name = "Semantics-adjective", type = SemanticsAdjective.class),
			@XmlElement(name = "SenseExamples", type = SenseExamples.class),
			@XmlElement(name = "SenseRelations", type = SenseRelations.class)
	})
	protected List<Object> sentimentOrPragmaticsOrSemanticsVerb;
	@XmlAttribute(name = "id", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String id;
	@XmlAttribute(name = "senseId")
	@XmlSchemaType(name = "anySimpleType")
	protected String senseId;
	@XmlAttribute(name = "provenance")
	@XmlSchemaType(name = "anySimpleType")
	protected String provenance;
	@XmlAttribute(name = "synset")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NMTOKEN")
	protected String synset;
	@XmlAttribute(name = "definition", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String definition;

	/**
	 * Gets the value of the sentimentOrPragmaticsOrSemanticsVerb property.
	 * <p>
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the sentimentOrPragmaticsOrSemanticsVerb property.
	 * <p>
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getSentimentOrPragmaticsOrSemanticsVerb().add(newItem);
	 * </pre>
	 * <p>
	 * <p>
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Sentiment }
	 * {@link Pragmatics }
	 * {@link SemanticsVerb }
	 * {@link SemanticsNoun }
	 * {@link SemanticsAdjective }
	 * {@link SenseExamples }
	 * {@link SenseRelations }
	 */
	public List<Object> getSentimentOrPragmaticsOrSemanticsVerb() {
		if (sentimentOrPragmaticsOrSemanticsVerb == null) {
			sentimentOrPragmaticsOrSemanticsVerb = new ArrayList<Object>();
		}
		return this.sentimentOrPragmaticsOrSemanticsVerb;
	}

	/**
	 * Gets the value of the id property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setId(String value) {
		this.id = value;
	}

	/**
	 * Gets the value of the senseId property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getSenseId() {
		return senseId;
	}

	/**
	 * Sets the value of the senseId property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setSenseId(String value) {
		this.senseId = value;
	}

	/**
	 * Gets the value of the provenance property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getProvenance() {
		return provenance;
	}

	/**
	 * Sets the value of the provenance property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setProvenance(String value) {
		this.provenance = value;
	}

	/**
	 * Gets the value of the synset property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getSynset() {
		return synset;
	}

	/**
	 * Sets the value of the synset property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setSynset(String value) {
		this.synset = value;
	}

	/**
	 * Gets the value of the definition property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getDefinition() {
		return definition;
	}

	/**
	 * Sets the value of the definition property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setDefinition(String value) {
		this.definition = value;
	}

}
