//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 01:30:51 PM CET 
//


package nl.willemsenmedia.utwente.anonymization.nlp.xml_objects;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}attlist.syntacticArgument"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "syntacticArgument")
public class SyntacticArgument {

	@XmlAttribute(name = "constituent")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String constituent;
	@XmlAttribute(name = "function")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String function;
	@XmlAttribute(name = "preposition")
	@XmlSchemaType(name = "anySimpleType")
	protected String preposition;
	@XmlAttribute(name = "complementizer")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String complementizer;

	/**
	 * Gets the value of the constituent property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getConstituent() {
		return constituent;
	}

	/**
	 * Sets the value of the constituent property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setConstituent(String value) {
		this.constituent = value;
	}

	/**
	 * Gets the value of the function property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getFunction() {
		return function;
	}

	/**
	 * Sets the value of the function property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setFunction(String value) {
		this.function = value;
	}

	/**
	 * Gets the value of the preposition property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getPreposition() {
		return preposition;
	}

	/**
	 * Sets the value of the preposition property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setPreposition(String value) {
		this.preposition = value;
	}

	/**
	 * Gets the value of the complementizer property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getComplementizer() {
		return complementizer;
	}

	/**
	 * Sets the value of the complementizer property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setComplementizer(String value) {
		this.complementizer = value;
	}

}
