//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 01:30:51 PM CET 
//


package nl.willemsenmedia.utwente.anonymization.nlp.xml_objects;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}attlist.WordForm"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "WordForm")
public class WordForm {

	@XmlAttribute(name = "article")
	@XmlSchemaType(name = "anySimpleType")
	protected String article;
	@XmlAttribute(name = "grammaticalNumber")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String grammaticalNumber;
	@XmlAttribute(name = "comparison")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String comparison;
	@XmlAttribute(name = "tense")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String tense;
	@XmlAttribute(name = "writtenForm", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String writtenForm;

	/**
	 * Gets the value of the article property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getArticle() {
		return article;
	}

	/**
	 * Sets the value of the article property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setArticle(String value) {
		this.article = value;
	}

	/**
	 * Gets the value of the grammaticalNumber property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getGrammaticalNumber() {
		return grammaticalNumber;
	}

	/**
	 * Sets the value of the grammaticalNumber property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setGrammaticalNumber(String value) {
		this.grammaticalNumber = value;
	}

	/**
	 * Gets the value of the comparison property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getComparison() {
		return comparison;
	}

	/**
	 * Sets the value of the comparison property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setComparison(String value) {
		this.comparison = value;
	}

	/**
	 * Gets the value of the tense property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getTense() {
		return tense;
	}

	/**
	 * Sets the value of the tense property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setTense(String value) {
		this.tense = value;
	}

	/**
	 * Gets the value of the writtenForm property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getWrittenForm() {
		return writtenForm;
	}

	/**
	 * Sets the value of the writtenForm property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setWrittenForm(String value) {
		this.writtenForm = value;
	}

}
