//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 01:30:51 PM CET 
//


package nl.willemsenmedia.utwente.anonymization.nlp_java.xml_objects;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}attlist.combiWord"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "combiWord")
public class CombiWord {

	@XmlAttribute(name = "partOfSpeech")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String partOfSpeech;
	@XmlAttribute(name = "lemma")
	@XmlSchemaType(name = "anySimpleType")
	protected String lemma;

	/**
	 * Gets the value of the partOfSpeech property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getPartOfSpeech() {
		return partOfSpeech;
	}

	/**
	 * Sets the value of the partOfSpeech property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setPartOfSpeech(String value) {
		this.partOfSpeech = value;
	}

	/**
	 * Gets the value of the lemma property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getLemma() {
		return lemma;
	}

	/**
	 * Sets the value of the lemma property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setLemma(String value) {
		this.lemma = value;
	}

}
