//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 01:30:51 PM CET 
//


package nl.willemsenmedia.utwente.anonymization.nlp_java.xml_objects;

import nl.willemsenmedia.utwente.anonymization.data.DataModifier;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}attlist.Lemma"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = "")
@XmlRootElement(name = "Lemma")
public class Lemma {

	@XmlAttribute(name = "writtenForm", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String writtenForm;
	@XmlAttribute(name = "mode")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String mode;

	/**
	 * Gets the value of the writtenForm property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getWrittenForm() {
		return writtenForm;
	}

	/**
	 * Sets the value of the writtenForm property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setWrittenForm(String value) {
		this.writtenForm = value;
	}

	/**
	 * Gets the value of the mode property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getMode() {
		return mode;
	}

	/**
	 * Sets the value of the mode property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setMode(String value) {
		this.mode = value;
	}

	// Manually added

	/**
	 * Gets the stem from the writtenForm
	 *
	 * @return Stem of the word
	 */
	public String getStem() {
		return DataModifier.getStem(writtenForm);
	}
}
