//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 01:30:51 PM CET 
//


package nl.willemsenmedia.utwente.anonymization.nlp_java.xml_objects;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}GlobalInformation"/>
 *         &lt;element ref="{}Lexicon"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"globalInformation",
		"lexicon"
})
@XmlRootElement(name = "LexicalResource")
public class LexicalResource {

	@XmlElement(name = "GlobalInformation", required = true)
	protected GlobalInformation globalInformation;
	@XmlElement(name = "Lexicon", required = true)
	protected Lexicon lexicon;

	/**
	 * Gets the value of the globalInformation property.
	 *
	 * @return possible object is
	 * {@link GlobalInformation }
	 */
	public GlobalInformation getGlobalInformation() {
		return globalInformation;
	}

	/**
	 * Sets the value of the globalInformation property.
	 *
	 * @param value allowed object is
	 *              {@link GlobalInformation }
	 */
	public void setGlobalInformation(GlobalInformation value) {
		this.globalInformation = value;
	}

	/**
	 * Gets the value of the lexicon property.
	 *
	 * @return possible object is
	 * {@link Lexicon }
	 */
	public Lexicon getLexicon() {
		return lexicon;
	}

	/**
	 * Sets the value of the lexicon property.
	 *
	 * @param value allowed object is
	 *              {@link Lexicon }
	 */
	public void setLexicon(Lexicon value) {
		this.lexicon = value;
	}

}
