//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 01:30:51 PM CET 
//


package nl.willemsenmedia.utwente.anonymization.nlp_java.xml_objects;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}attlist.Morphology"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Morphology")
public class Morphology {

	@XmlAttribute(name = "morphoType")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String morphoType;
	@XmlAttribute(name = "comparisonType")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String comparisonType;
	@XmlAttribute(name = "declinable")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String declinable;
	@XmlAttribute(name = "separability")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String separability;

	/**
	 * Gets the value of the morphoType property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getMorphoType() {
		return morphoType;
	}

	/**
	 * Sets the value of the morphoType property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setMorphoType(String value) {
		this.morphoType = value;
	}

	/**
	 * Gets the value of the comparisonType property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getComparisonType() {
		return comparisonType;
	}

	/**
	 * Sets the value of the comparisonType property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setComparisonType(String value) {
		this.comparisonType = value;
	}

	/**
	 * Gets the value of the declinable property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getDeclinable() {
		return declinable;
	}

	/**
	 * Sets the value of the declinable property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setDeclinable(String value) {
		this.declinable = value;
	}

	/**
	 * Gets the value of the separability property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getSeparability() {
		return separability;
	}

	/**
	 * Sets the value of the separability property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setSeparability(String value) {
		this.separability = value;
	}

}
