//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 01:30:51 PM CET 
//


package nl.willemsenmedia.utwente.anonymization.nlp_java.xml_objects;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Domains" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.Pragmatics"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"domains"
})
@XmlRootElement(name = "Pragmatics")
public class Pragmatics {

	@XmlElement(name = "Domains")
	protected List<Domains> domains;
	@XmlAttribute(name = "chronology")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String chronology;
	@XmlAttribute(name = "connotation")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String connotation;
	@XmlAttribute(name = "geography")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String geography;
	@XmlAttribute(name = "register")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String register;

	/**
	 * Gets the value of the domains property.
	 * <p>
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the domains property.
	 * <p>
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getDomains().add(newItem);
	 * </pre>
	 * <p>
	 * <p>
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Domains }
	 */
	public List<Domains> getDomains() {
		if (domains == null) {
			domains = new ArrayList<Domains>();
		}
		return this.domains;
	}

	/**
	 * Gets the value of the chronology property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getChronology() {
		return chronology;
	}

	/**
	 * Sets the value of the chronology property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setChronology(String value) {
		this.chronology = value;
	}

	/**
	 * Gets the value of the connotation property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getConnotation() {
		return connotation;
	}

	/**
	 * Sets the value of the connotation property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setConnotation(String value) {
		this.connotation = value;
	}

	/**
	 * Gets the value of the geography property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getGeography() {
		return geography;
	}

	/**
	 * Sets the value of the geography property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setGeography(String value) {
		this.geography = value;
	}

	/**
	 * Gets the value of the register property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getRegister() {
		return register;
	}

	/**
	 * Sets the value of the register property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setRegister(String value) {
		this.register = value;
	}

}
