//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 01:30:51 PM CET 
//


package nl.willemsenmedia.utwente.anonymization.nlp_java.xml_objects;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}semanticShifts-adjective" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.Semantics-adjective"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"semanticShiftsAdjective"
})
@XmlRootElement(name = "Semantics-adjective")
public class SemanticsAdjective {

	@XmlElement(name = "semanticShifts-adjective")
	protected List<SemanticShiftsAdjective> semanticShiftsAdjective;
	@XmlAttribute(name = "semanticType")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String semanticType;

	/**
	 * Gets the value of the semanticShiftsAdjective property.
	 * <p>
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the semanticShiftsAdjective property.
	 * <p>
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getSemanticShiftsAdjective().add(newItem);
	 * </pre>
	 * <p>
	 * <p>
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link SemanticShiftsAdjective }
	 */
	public List<SemanticShiftsAdjective> getSemanticShiftsAdjective() {
		if (semanticShiftsAdjective == null) {
			semanticShiftsAdjective = new ArrayList<SemanticShiftsAdjective>();
		}
		return this.semanticShiftsAdjective;
	}

	/**
	 * Gets the value of the semanticType property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getSemanticType() {
		return semanticType;
	}

	/**
	 * Sets the value of the semanticType property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setSemanticType(String value) {
		this.semanticType = value;
	}

}
