//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.25 at 03:24:35 PM CET 
//


package nl.willemsenmedia.utwente.anonymization.settings;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the generated package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _SettingsSettingEntry_QNAME = new QName("", "entry");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Settings }
	 */
	public Settings createSettings() {
		return new Settings();
	}

	/**
	 * Create an instance of {@link Settings.Setting }
	 */
	public Settings.Setting createSettingsSetting() {
		return new Settings.Setting();
	}

	/**
	 * Create an instance of {@link Settings.Setting.Entry }
	 */
	public Settings.Setting.Entry createSettingsSettingEntry() {
		return new Settings.Setting.Entry();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Settings.Setting.Entry }{@code >}}
	 */
	@XmlElementDecl(namespace = "", name = "entry", scope = Settings.Setting.class)
	public JAXBElement<Settings.Setting.Entry> createSettingsSettingEntry(Settings.Setting.Entry value) {
		return new JAXBElement<>(_SettingsSettingEntry_QNAME, Settings.Setting.Entry.class, Settings.Setting.class, value);
	}

}
