//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.25 at 03:24:35 PM CET 
//


package nl.willemsenmedia.utwente.anonymization.settings;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for settingsType.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="settingsType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="java.lang.Boolean"/>
 *     &lt;enumeration value="java.lang.Integer"/>
 *     &lt;enumeration value="java.lang.String"/>
 *     &lt;enumeration value="java.util.Map"/>
 *     &lt;enumeration value="nl.willemsenmedia.utwente.anonymization.data.handling.AnonymizationTechnique"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "settingsType")
@XmlEnum
public enum SettingsType {

	@XmlEnumValue("java.lang.Boolean")
	JAVA_LANG_BOOLEAN("java.lang.Boolean"),
	@XmlEnumValue("java.lang.Integer")
	JAVA_LANG_INTEGER("java.lang.Integer"),
	@XmlEnumValue("java.lang.String")
	JAVA_LANG_STRING("java.lang.String"),
	@XmlEnumValue("java.util.Map")
	JAVA_UTIL_MAP("java.util.Map"),
	@XmlEnumValue("nl.willemsenmedia.utwente.anonymization.data.handling.AnonymizationTechnique")
	NL_WILLEMSENMEDIA_UTWENTE_ANONYMIZATION_DATA_HANDLING_ANONYMIZATION_TECHNIQUE("nl.willemsenmedia.utwente.anonymization.data.handling.AnonymizationTechnique");
	private final String value;

	SettingsType(String v) {
		value = v;
	}

	public static SettingsType fromValue(String v) {
		for (SettingsType c : SettingsType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

	public String value() {
		return value;
	}

}
