//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.25 at 03:24:35 PM CET 
//


package nl.willemsenmedia.utwente.anonymization.settings;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.Property;
import javafx.beans.property.StringProperty;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="setting" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="entry" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="regex_search" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="regex_replace" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="screenname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="type" type="{}settingsType" default="java.lang.Boolean" />
 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="overwritable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = "", propOrder = {
		"setting"
})
@XmlRootElement(name = "settings")
public class Settings {

	@XmlElement(required = true)
	protected List<Settings.Setting> setting;
	protected Map<String, Setting> map;

	/**
	 * Gets the value of the setting property.
	 * <p>
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the setting property.
	 * <p>
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getSetting().add(newItem);
	 * </pre>
	 * <p>
	 * <p>
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Settings.Setting }
	 */
	public List<Settings.Setting> getSetting() {
		if (setting == null) {
			setting = new ArrayList<>();
		}
		return this.setting;
	}

	public Map<String, Setting> getSettingsMap() {
		if (map == null || map.size() == 0) {
			map = new HashMap<>();
			for (Setting setting : this.setting) {
				map.put(setting.getName(), setting);
			}
		}
		return this.map;
	}


	/**
	 * <p>Java class for anonymous complex type.
	 * <p>
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * <p>
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="entry" maxOccurs="unbounded" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
	 *                 &lt;attribute name="regex_search" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="regex_replace" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *       &lt;attribute name="screenname" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *       &lt;attribute name="type" type="{}settingsType" default="java.lang.Boolean" />
	 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *       &lt;attribute name="overwritable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 */
	@XmlAccessorType(XmlAccessType.NONE)
	@XmlType(name = "", propOrder = {
			"content"
	})
	public static class Setting {

		@XmlElementRef(name = "entry", type = JAXBElement.class, required = false)
		@XmlMixed
		protected List<Serializable> content;
		@XmlAttribute(name = "name", required = true)
		protected String name;
		@XmlAttribute(name = "screenname")
		protected String screenname;
		@XmlAttribute(name = "type")
		protected SettingsType type;
		@XmlAttribute(name = "value")
		protected String value;
		@XmlAttribute(name = "overwritable")
		protected Boolean overwritable;
		private Property view;

		/**
		 * Gets the value of the content property.
		 * <p>
		 * <p>
		 * This accessor method returns a reference to the live list,
		 * not a snapshot. Therefore any modification you make to the
		 * returned list will be present inside the JAXB object.
		 * This is why there is not a <CODE>set</CODE> method for the content property.
		 * <p>
		 * <p>
		 * For example, to add a new item, do as follows:
		 * <pre>
		 *    getContent().add(newItem);
		 * </pre>
		 * <p>
		 * <p>
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link String }
		 * {@link JAXBElement }{@code <}{@link Settings.Setting.Entry }{@code >}
		 */
		public List<Serializable> getContent() {
			if (content == null) {
				content = new ArrayList<>();
			}
			return this.content;
		}

		/**
		 * Gets the value of the name property.
		 *
		 * @return possible object is
		 * {@link String }
		 */
		public String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 *
		 * @param value allowed object is
		 *              {@link String }
		 */
		public void setName(String value) {
			this.name = value;
		}

		/**
		 * Gets the value of the screenname property.
		 *
		 * @return possible object is
		 * {@link String }
		 */
		public String getScreenname() {
			if (screenname == null) {
				screenname = name.replace("_", " ");
				screenname = screenname.substring(0, 1).toUpperCase() + screenname.substring(1);
			}
			return screenname;
		}

		/**
		 * Sets the value of the screenname property.
		 *
		 * @param value allowed object is
		 *              {@link String }
		 */
		public void setScreenname(String value) {
			this.screenname = value;
		}

		/**
		 * Gets the value of the type property.
		 *
		 * @return possible object is
		 * {@link SettingsType }
		 */
		public SettingsType getType() {
			if (type == null) {
				return SettingsType.JAVA_LANG_BOOLEAN;
			} else {
				return type;
			}
		}

		/**
		 * Sets the value of the type property.
		 *
		 * @param value allowed object is
		 *              {@link SettingsType }
		 */
		public void setType(SettingsType value) {
			this.type = value;
		}

		/**
		 * Gets the value of the value property.
		 *
		 * @return possible object is
		 * {@link String }
		 */
		public String getValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 *
		 * @param value allowed object is
		 *              {@link String }
		 */
		public void setValue(String value) {
			this.value = value;
		}

		public void updateView() {
			if (view instanceof StringProperty) {
				((StringProperty) view).setValue(getValue());
			} else if (view instanceof BooleanProperty) {
				((BooleanProperty) view).setValue(Boolean.parseBoolean(getValue()));
			} else {
				throw new RuntimeException("Unknown type of property: " + view.getClass().getSimpleName());
			}
		}

		/**
		 * Gets the value of the overwritable property.
		 *
		 * @return possible object is
		 * {@link Boolean }
		 */
		public boolean isOverwritable() {
			if (overwritable == null) {
				return false;
			} else {
				return overwritable;
			}
		}

		/**
		 * Sets the value of the overwritable property.
		 *
		 * @param value allowed object is
		 *              {@link Boolean }
		 */
		public void setOverwritable(Boolean value) {
			this.overwritable = value;
		}

		public void addViewUpdater(Property viewProperty) {
			this.view = viewProperty;
		}


		/**
		 * <p>Java class for anonymous complex type.
		 * <p>
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * <p>
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
		 *       &lt;attribute name="regex_search" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="regex_replace" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class Entry {

			@XmlValue
			protected String value;
			@XmlAttribute(name = "regex_search", required = true)
			protected String regexSearch;
			@XmlAttribute(name = "regex_replace", required = true)
			protected String regexReplace;
			@XmlAttribute(name = "comment")
			protected String comment;

			/**
			 * Gets the value of the value property.
			 *
			 * @return possible object is
			 * {@link String }
			 */
			public String getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 *
			 * @param value allowed object is
			 *              {@link String }
			 */
			public void setValue(String value) {
				this.value = value;
			}

			/**
			 * Gets the value of the regexSearch property.
			 *
			 * @return possible object is
			 * {@link String }
			 */
			public String getRegexSearch() {
				return regexSearch;
			}

			/**
			 * Sets the value of the regexSearch property.
			 *
			 * @param value allowed object is
			 *              {@link String }
			 */
			public void setRegexSearch(String value) {
				this.regexSearch = value;
			}

			/**
			 * Gets the value of the regexReplace property.
			 *
			 * @return possible object is
			 * {@link String }
			 */
			public String getRegexReplace() {
				return regexReplace;
			}

			/**
			 * Sets the value of the regexReplace property.
			 *
			 * @param value allowed object is
			 *              {@link String }
			 */
			public void setRegexReplace(String value) {
				this.regexReplace = value;
			}

			/**
			 * Gets the value of the comment property.
			 *
			 * @return possible object is
			 * {@link String }
			 */
			public String getComment() {
				if (comment == null) {
					return "";
				} else {
					return comment;
				}
			}

			/**
			 * Sets the value of the comment property.
			 *
			 * @param value allowed object is
			 *              {@link String }
			 */
			public void setComment(String value) {
				this.comment = value;
			}

		}

	}

}
